name: BUILD

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Builds application
        run: |
          npm i
          npm run build
      - uses: actions/upload-artifact@master
        with:
          name: artifact
          path: dist
