name: CI

on: [push]

jobs:

    lint:
            runs-on: ubuntu-latest

            steps:
                    run: npm run lint


    build:
            runs-on: ubuntu-latest
            steps:
                    run: npm run build

