name: CI

on: [push]

jobs:

    lint:
            runs-on: ubuntu-latest

            steps:
                    - uses: actions/checkout@v1
                    - name: Runs linter
                     run: npm run lint


    build:
            runs-on: ubuntu-latest
            steps:
                    - uses: actions/checkout@v1
                    - name: Runs build
                     run: npm run build

