name: DEPLOY

on: 
  push:
    branches:
      - master

jobs:
  install-push-dir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installs push dir
        run: npm i push-dir

  deploy:
    needs: [build, install-push-dir]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: artifact
          path: dist
      - uses: actions/checkout@v2
      - name: Builds application
        run: npm run deploy
