name: TEST

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Runs linter
      run: |
        npm i
        npm run lint

  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Runs test build
        run: |
          npm i
          npm run build
